Feat/#1
CSID-DGU/2022-1-CECD3-Jenga-6 pull request #4
Opened 2022-10-04 18:37 UTC by minnseong

## 💡 왜 PR을 하셨나요?
resolve #1

## 🤩 개요
Ec2, S3, IGW 조회 테스트 및 엔티티 생성

## 🧑‍💻 작업 사항
Ec2, S3, IGW 조회 테스트 및 엔티티 생성

## ❗️ PR 전 확인
- [ ] Test를 진행하셨나요?

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.

2022-10-04 18:38 UTC, choiyunh approved these changes
"The only way to go fast, is to go well." 👍

2022-10-04 18:39 UTC, mincastle98 approved these changes
LGTM😃

2022-10-04 18:48 UTC, mincastle98 requested changes
try-with-resource문에 불필요한 세미콜론 포함되어 있는 부분 반영 부탁드려요ㅎㅎ

2022-10-04 18:48 UTC, mincastle98 commented on src/test/java/com/jenga/weather/domain/ec2/Ec2Test.java
> +                .build();) {
build() 다음에 오는 세미콜론은 없어도 될 것 같습니다! 다른 클래스에도 전부 동일하게 적용되어 있네요🤣

2022-10-05 05:34 UTC, minnseong commented on src/test/java/com/jenga/weather/domain/ec2/Ec2Test.java
> +                .build();) {
수정하였습니다!

2022-10-05 05:38 UTC, mincastle98 approved these changes

2022-10-05 05:38 UTC, merged