Feat/#2
CSID-DGU/2022-1-CECD3-Jenga-6 pull request #5
Opened 2022-10-04 18:38 UTC by mincastle98

## 💡 왜 PR을 하셨나요?
resolve #{이슈번호}

## 🤩 개요
RDS, ELB의 엔티티 생성을 위해 SDK를 통해 정보를 가져오고 그에 맞춰 엔티티를 생성한다.

## 🧑‍💻 작업 사항
RDS, ELB 조회 테스트 및 엔티티 생성 

## ❗️ PR 전 확인
- [x] Test를 진행하셨나요?

## 📖 참고 사항
공유할 내용, 레퍼런스, 추가로 발생할 것으로 예상되는 이슈, 스크린샷 등을 넣어 주세요.

2022-10-04 18:41 UTC, choiyunh approved these changes
LGTM 👍

2022-10-04 18:44 UTC, minnseong requested changes
ElbTest, RdsTest에 catch문 빠지신 것 확인 부탁드립니다!!

2022-10-04 18:44 UTC, minnseong commented on src/test/java/com/jenga/weather/domain/elb/ElbTest.java
> +        try (ElasticLoadBalancingV2Client elb = ElasticLoadBalancingV2Client.builder()
try with resources를 사용하여 자원회수를 하신 것 매우 나이스하십니다..👍🏻

2022-10-04 18:44 UTC, minnseong commented on src/test/java/com/jenga/weather/domain/elb/ElbTest.java
> +        }
제 의견이지만, catch 부분이 빠지신 것 같습니다..!

2022-10-04 18:48 UTC, choiyunh requested changes
Please check and reflect the comments 👍

2022-10-04 18:48 UTC, choiyunh commented on src/test/java/com/jenga/weather/domain/elb/ElbTest.java
> +        }
IMO,,,, the catch seems to be missing.

2022-10-04 18:51 UTC, choiyunh commented
resolve 이슈번호 확인바랍니다.

2022-10-05 05:39 UTC, minnseong approved these changes

2022-10-05 05:39 UTC, choiyunh approved these changes

2022-10-05 05:40 UTC, merged